on:
  - push

name: Continuous Integration

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: xdebug
          extensions: intl, gd
          tools: psalm:4.30, phpcs:3.7, phpunit:9.5, composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.2.1"
          version: 2
          args: --ignore-platform-reqs
        env:
          ACTION_PHP_VERSION: 8.2.1

      - name: Run code styling with PHPCS
        run: phpcs

      - name: Run header checks with DocHeader
        run: ./vendor/bin/docheader check src/ test/

      - name: Run static code analysis with psalm
        run: psalm --config=psalm.xml

      - name: Run unit tests with PHPUnit
        run: phpunit --coverage-clover build/logs/clover.xml
        env:
          XDEBUG_MODE: coverage

      - name: Run coverage
        run: ./vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
